name: Terraform-Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform-Check
        run: echo "Code is ready to deploy using OIDC"
